format = """
$os\

$shlvl\

$username\
$hostname\
$localip\

$directory\

$fill\

$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$gleam\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$quarto\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$typst\
$vlang\
$vagrant\
$zig\

$buf\
$nix_shell\
$conda\
$meson\
$spack\

$docker_context\

$singularity\
$kubernetes\

$vcsh\
$fossil_branch\
$fossil_metrics\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$pijul_channel\

$cmd_duration\
$time\

$line_break\

$shell\
$character\
"""


palette = 'custom_colors'

[palettes.custom_colors]
color_shlvl = '#F0D9CC'
color_user = '#F5EBC8'
color_ssh = '#EBD8DC'

color_fill = '#D5D5D7'

color_program_language = '#D4E4F1'
color_package_manager = '#C9D3C0'
color_container = '#CBE5E0'
color_version_control = '#F5EBC8'
color_duration = '#D1C9FA'
color_time = '#DBD3DC'

color_shell = '#F0EFEB'
color_character = '#6868AC'


# Pantone Color of the Year 2026
color_cloud_dancer = '#F0EFEB'

color_lemon_icing = '#F5EBC8'
color_nimbus_cloud = '#D5D5D7'
color_raindrop_on_roses = '#EBD8DC'
color_ice_melt = '#D4E4F1'
color_peach_dust = '#F0D9CC'
color_almost_aqua = '#C9D3C0'
color_orchid_tint = '#DBD3DC'
color_light_purple = '#D1C9FA'
color_light_teal = '#CBE5E0'

color_iris_orchid = '#A867A4'
color_capri = '#45BBCA'
color_kiwi_colada = '#BDCA23'
color_sunny_lime = '#E0EE88'
color_bright_marigold = '#FF8E00'
color_paradise_pink = '#E4465E'
color_blazing_yellow = '#FEE816'

color_stretch_limo = '#2B2C30'
# end of 2026


# Pantone Color of the Year 2022
color_very_peri = '#6868AC'

color_burnished_lilac = '#C6AAAF'
color_lotus = '#E3C1BE'
color_muted_clay = '#D3927D'
color_dried_moss = '#CDB97D'
color_granite_green = '#85A094'
color_hawthorn_rose = '#894B5D'
color_elderberry = '#A0838F'

color_anthracite = '#29282D'
color_volcanic_glass = '#625C60'
color_deep_taupe = '#7D6461'
color_plaza_taupe = '#AEA392'
color_white_sand = '#DBD3CF'
color_petrified_oak = '#8E7960'
color_cloud_dancer_1 = '#F1EDE9'
# end of 2022


# Pantone Color of the Year 2018
color_ultra_violet = '#6E5B98'

color_ether = '#A0B9BC'
color_weeping_willow = '#B1AD7E'
color_tradewinds = '#869098'

color_misty_lilac = '#BBB6C5'
color_deauville_mauve = '#AB9294'

color_dusty_lavender = '#9D789B'
color_lavender_violet = '#7A81A8'

color_jacaranda = '#868FC7'
color_rhapsody = '#A28BA9'
# end of 2018


[os]
disabled = false
format = '$symbol'

[os.symbols]
Windows = '[Óò™ ](#14ABCD)' # light: (#0078D4), dark: (#14ABCD)
Ubuntu = '[Û∞ïà ](#E95420)'
SUSE = '[Ôåî ](#30BA78)'
Raspbian = '[ÓΩú ](#CD2255)'
Mint = '[Û∞£≠ ](#8CBF4B)'
Macos = '[Û∞Äµ ](white)'
Manjaro = '[Ôåí ](#36BFA4)'
Linux = '[ÓØÜ ](white)'
Gentoo = '[Û∞£® ](#DDDFFF)'
Fedora = '[Û∞£õ ](#51A2DA)'
Alpine = '[ÔåÄ ](#0E597F)'
Amazon = '[Ôâ∞ ](white)'
Android = '[Óúé ](#34A853)'
Arch = '[Û∞£á ](#1793d1)'
Artix = '[Ôåü ](#12A0CC)'
EndeavourOS = '[Ôå¢ ](#7F3FBF)'
CentOS = '[ÔåÑ ](#A34E8D)'
Debian = '[Û∞£ö ](#A80030)'
Redhat = '[Û±Ñõ ](#EE0000)'
RedHatEnterprise = '[Û±Ñõ ](#EE0000)'
Pop = '[Ôå™ ](#66AFC0)'
NixOS = '[Ó°É ](#7DB7E0)' # other: (#4F74BD)


[shlvl]
disabled = false
threshold = 2
symbol = 'ÔÑÉ'
style = 'color_shlvl'
format = '[ $symbol$shlvl]($style)'


[username]
disabled = false
style_user = 'bold color_user'
style_root = 'bold bright-yellow'
format = '[ $user]($style)'
aliases = { 'Administrator' = 'Û∞¢è ' }


[hostname]
disabled = false
ssh_symbol = 'Û∞åó '
style = 'color_ssh'
format = '[@$hostname]($style)'

[localip]
disabled = true
style = 'color_ssh'
format = '[@$localipv4]($style)'


[directory]
disabled = false
style = 'yellow'
read_only = 'Û∞åæ '
read_only_style = 'red'
format = '[ ÔÑï  ]($style)[$path ]()[$read_only]($read_only_style)'
truncate_to_repo = true
truncation_length = 6
truncation_symbol = '‚Ä¶/'

[directory.substitutions]
'Documents' = 'Û∞àô '
'Downloads' = 'ÔÄô '
'Music' = 'ÔÄÅ '
'Pictures' = 'ÔÄæ '
'Developer' = 'Û∞≤ã '


[fill]
# disabled = true
# 'ÓÆä Ó∞á ÓØ∫ Ó∞á '
symbol = 'Ó∞á ÓÆä ÓØ∫ ÓÆä '
style = 'color_fill'


# Programming Languages

[c]
# disabled = true
symbol = 'Óù± '
style = 'color_program_language'
format = '[ $symbol($version)]($style)'

[cmake]
# disabled = true
symbol = 'Û∞î∑ '
style = 'color_program_language'
format = '[ $symbol($version)]($style)'

[cobol]
disabled = true
symbol = 'Û±ãæ '
style = 'color_program_language'
format = '[ $symbol($version)]($style)'

[daml]
disabled = true
symbol = 'Û∞≤á '
style = 'color_program_language'
format = '[ $symbol($version)]($style)'

[dart]
disabled = true
symbol = 'Óôå '
style = 'color_program_language'
format = '[ $symbol($version)]($style)'

[deno]
disabled = true
symbol = 'ÓüÄ '
style = 'color_program_language'
format = '[ $symbol($version)]($style)'

[dotnet]
disabled = true
symbol = 'Û∞™Æ '
style = 'color_program_language'
format = '[ $symbol($version)(Û∞ìæ $tfm)]($style)'

[elixir]
disabled = true
symbol = 'Óüç '
style = 'color_program_language'
format = '[ $symbol($version \(OTP $otp_version\))]($style)'

[elm]
disabled = true
symbol = 'Óüé '
style = 'color_program_language'
format = '[ $symbol($version)]($style)'

[erlang]
disabled = true
symbol = 'Óû± '
style = 'color_program_language'
format = '[ $symbol($version)]($style)'

[fennel]
disabled = true
symbol = 'ÓöØ '
style = 'color_program_language'
format = '[ $symbol($version)]($style)'

[gleam]
disabled = true
symbol = 'ÔÄÖ '
style = 'color_program_language'
format = '[ $symbol($version)]($style)'

[golang]
# disabled = true
symbol = 'Óò¶ '
style = 'color_program_language'
format = '[ $symbol($version)]($style)'

[guix_shell]
disabled = true
symbol = 'Ôå• '
style = 'color_program_language'
format = '[ $symbol($version)]($style)'

[haskell]
disabled = true
symbol = 'Óù∑ '
style = 'color_program_language'
format = '[ $symbol($version)]($style)'

[haxe]
disabled = true
symbol = 'Óô¶ '
style = 'color_program_language'
format = '[ $symbol($version)]($style)'

[helm]
disabled = true
symbol = 'Óüª '
style = 'color_program_language'
format = '[ $symbol($version)]($style)'

[java]
# disabled = true
symbol = 'Óâñ '
style = 'color_program_language'
format = '[ $symbol($version)]($style)'

[julia]
disabled = true
symbol = 'Óò§ '
style = 'color_program_language'
format = '[ $symbol($version)]($style)'

[kotlin]
# disabled = true
symbol = 'Óò¥ '
style = 'color_program_language'
format = '[ $symbol($version)]($style)'

[gradle]
disabled = true
symbol = 'Óô† '
style = 'color_program_language'
format = '[ $symbol($version)]($style)'

[lua]
disabled = true
symbol = 'Óò† '
style = 'color_program_language'
format = '[ $symbol($version)]($style)'

[nim]
disabled = true
symbol = 'Óô∑ '
style = 'color_program_language'
format = '[ $symbol($version)]($style)'

[nodejs]
# disabled = true
symbol = 'Û∞éô '
style = 'color_program_language'
format = '[ $symbol($version)]($style)'

[ocaml]
disabled = true
symbol = 'Óô∫ '
style = 'color_program_language'
format = '[ $symbol($version)(\($switch_indicator$switch_name\))]($style)'

[opa]
disabled = true
symbol = 'OPA '
style = 'color_program_language'
format = '[ $symbol($version)]($style)'

[perl]
disabled = true
symbol = 'Óù© '
style = 'color_program_language'
format = '[ $symbol($version)]($style)'

[php]
disabled = true
symbol = 'Óòà '
style = 'color_program_language'
format = '[ $symbol($version)]($style)'

[pulumi]
disabled = true
symbol = 'Ó°≥ '
style = 'color_program_language'
format = '[ $symbol($username@)$stack]($style)'

[purescript]
disabled = true
symbol = 'Óò∞ '
style = 'color_program_language'
format = '[ $symbol($version)]($style)'

[python]
# disabled = true
symbol = 'Û∞å† '
style = 'color_program_language'
format = '[ $symbol($version)]($style)'

[quarto]
disabled = true
symbol = '‚®Å '
style = 'color_program_language'
format = '[ $symbol($version)]($style)'

[raku]
disabled = true
symbol = 'Óäé '
style = 'color_program_language'
format = '[ $symbol($version-$vm_version)]($style)'

[rlang]
disabled = true
symbol = 'Óöä '
style = 'color_program_language'
format = '[ $symbol($version)]($style)'

[ruby]
disabled = true
symbol = 'ÓòÖ '
style = 'color_program_language'
format = '[ $symbol($version)]($style)'

[rust]
# disabled = true
symbol = 'Óöã '
style = 'color_program_language'
format = '[ $symbol($version)]($style)'

[scala]
disabled = true
symbol = 'Óöé '
style = 'color_program_language'
format = '[ $symbol($version)]($style)'

[solidity]
disabled = true
symbol = 'Ó¢¶ '
style = 'color_program_language'
format = '[ $symbol($version)]($style)'

[swift]
disabled = true
symbol = 'Óöô '
style = 'color_program_language'
format = '[ $symbol($version)]($style)'

[terraform]
disabled = true
symbol = 'Óöö '
style = 'color_program_language'
format = '[ $symbol($version)$workspace]($style)'

[typst]
disabled = true
symbol = 'Ôçø '
style = 'color_program_language'
format = '[ $symbol($version)]($style)'

[vlang]
disabled = true
symbol = 'Óö¨ '
style = 'color_program_language'
format = '[ $symbol($version)]($style)'

[vagrant]
disabled = true
symbol = 'Ó£ê '
style = 'color_program_language'
format = '[ $symbol($version)]($style)'

[zig]
disabled = true
symbol = 'Óö© '
style = 'color_program_language'
format = '[ $symbol($version)]($style)'


# Package Managers

[buf]
disabled = true
symbol = 'Û∞öâ '
style = 'color_package_manager'
format = '[ $symbol($version)]($style)'

[nix_shell]
disabled = true
symbol = 'Ó°É '
style = 'color_package_manager'
format = '[ $symbol$state( \($name\))]($style)'

[conda]
# disabled = true
symbol = 'Óúï '
style = 'color_package_manager'
format = '[ $symbol$environment]($style)'

[meson]
# disabled = true
symbol = 'Û∞Øô '
style = 'color_package_manager'
format = '[ $symbol$project]($style)'

[spack]
disabled = true
symbol = 'Ó¢™ '
style = 'color_package_manager'
format = '[ $symbol$environment]($style)'


# Containers

[docker_context]
disabled = false
symbol = 'Ôåà '
style = 'bold blue'
format = '[ $symbol$context]($style)'


[singularity]
disabled = true
symbol = 'Ôà≥ '
style = 'color_container'
format = '[ $symbol\[$env\]]($style)'

[kubernetes]
disabled = true
symbol = 'Û±Éæ '
style = 'color_container'
format = '[ $symbol$context( \($namespace\))]($style)'


# Version Control

[vcsh]
disabled = true
symbol = 'Ôëø '
style = 'color_version_control'
format = '[ $symbol$repo]($style)'


[fossil_branch]
disabled = true
symbol = 'Ôêò '
style = 'color_version_control'
format = '[ $symbol$branch]($style)'

[fossil_metrics]
disabled = true
format = '( [+$added]($added_style))( [-$deleted]($deleted_style))'


[git_branch]
disabled = false
symbol = 'Ôêò '
style = 'color_version_control'
format = '[ $symbol$branch]($style)'

[git_commit]
disabled = false
only_detached = false 
style = 'color_version_control'
format = '[ $hash]($style)'

[git_state]
disabled = false
style = 'color_version_control'
format = '[ \($state( $progress_current/$progress_total)]\)]($style)'

[git_metrics]
disabled = true
format = '( [+$added]($added_style))( [-$deleted]($deleted_style))'

[git_status]
disabled = false
style = 'color_version_control'
format = '[( $all_status$ahead_behind)]($style)'

[hg_branch]
disabled = true
symbol = 'Ôêò '
style = 'color_version_control'
format = '[ $symbol$branch(:$topic)]($style) '

[pijul_channel]
disabled = true
symbol = 'Ôêò '
style = 'color_version_control'
format = '[ $symbol$channel]($style)'


[cmd_duration]
disabled = false
style = 'color_duration'
format = '[ Û∞ö≠ $duration]($style)'

[time]
disabled = false
time_format = '%T'
style = 'color_time'
format = '[ ÔÄó $time]($style)'


[line_break]
disabled = false


[shell]
disabled = false
bash_indicator = 'Û∞ØÆ '
fish_indicator = 'ÓπÅ '
zsh_indicator = 'Û∞∞∂ '
powershell_indicator = 'ÓØá '
ion_indicator = 'Û∞∞É '
elvish_indicator = 'Û∞Ø∑ '
tcsh_indicator = 'Û∞∞§ '
xonsh_indicator = 'Û∞∞∞ '
cmd_indicator = 'ÓØÑ '
nu_indicator = 'ùõé '
unknown_indicator = 'Ó¨≤ '
style = 'color_shell'
format = '[$indicator ]($style)'

[character]
disabled = false
format = '$symbol '
success_symbol = '[ÔÜí ](color_character)'
error_symbol = '[ÔÅú ](red)'
vimcmd_symbol = '[Û∞∫ï ](color_character)' # Ôáé
vimcmd_replace_one_symbol = '[Û∞™• ](purple)'
vimcmd_replace_symbol = '[Û∞™• ](purple)'
vimcmd_visual_symbol = '[Û∞Æï ](yellow)'
