[general]
import = ["~/.config/alacritty/themes/catppuccin-frappe.toml"]

[terminal.shell]
program = "zsh"
args = ["--login"]


[env]
TERM = "xterm-256color"


[cursor]
[cursor.style]
shape = "Beam"
blinking = "on"


[window]
dynamic_padding = true
decorations = "Transparent"
opacity = 0.6
# blur = true
startup_mode = "Windowed"

[window.dimensions]
columns = 128
lines = 32

# [window.padding]
# x = 2
# y = 2


[font]
size = 12.0

[font.normal]
family = "Maple Mono NF CN"
style = "Regular"

[font.bold]
family = "Maple Mono NF CN"
style = "Bold"

[font.italic]
family = "Maple Mono NF CN"
style = "Italic"

[font.bold_italic]
family = "Maple Mono NF CN"
style = "Bold Italic"
