[terminal.shell]
program = "zsh"
args = [ "--login" ]


[env]
TERM = "xterm-256color"


[cursor]
[cursor.style]
shape = "Beam"
blinking = "on"


[window]
dynamic_padding = true
decorations = "Transparent"
opacity = 0.6
# blur = true
startup_mode = "Windowed"

[window.dimensions]
columns = 128
lines = 32

# [window.padding]
# x = 2
# y = 2


[font]
size = 12.0

[font.normal]
family = "Maple Mono NF CN"
style = "Regular"

[font.bold]
family = "Maple Mono NF CN"
style = "Bold"

[font.italic]
family = "Maple Mono NF CN"
style = "Italic"

[font.bold_italic]
family = "Maple Mono NF CN"
style = "Bold Italic"


# Catppuccin Frappe
[colors.primary]
# background = "#303446"
foreground = "#c6d0f5"
# dim_foreground = "#838ba7"
bright_foreground = "#c6d0f5"

[colors.cursor]
text = "#303446"
cursor = "#f2d5cf"

[colors.vi_mode_cursor]
text = "#303446"
cursor = "#babbf1"

[colors.search.matches]
foreground = "#303446"
background = "#a5adce"

[colors.search.focused_match]
foreground = "#303446"
background = "#a6d189"

[colors.footer_bar]
foreground = "#303446"
background = "#a5adce"

[colors.hints.start]
foreground = "#303446"
background = "#e5c890"

[colors.hints.end]
foreground = "#303446"
background = "#a5adce"

[colors.selection]
text = "#303446"
background = "#f2d5cf"

[colors.normal]
black = "#51576d"
red = "#e78284"
green = "#a6d189"
yellow = "#e5c890"
blue = "#8caaee"
magenta = "#f4b8e4"
cyan = "#81c8be"
white = "#b5bfe2"

[colors.bright]
black = "#626880"
red = "#e78284"
green = "#a6d189"
yellow = "#e5c890"
blue = "#8caaee"
magenta = "#f4b8e4"
cyan = "#81c8be"
white = "#a5adce"

[[colors.indexed_colors]]
index = 16
color = "#ef9f76"

[[colors.indexed_colors]]
index = 17
color = "#f2d5cf"
# End of Catppuccin Frappe

